description: Attach the workspace at ~/attached_workspace and list its contents
steps:
    - attach_workspace:
        at: ~/attached_workspace
    - run:
        name: Attached workspace contents
        command: ls ~/attached_workspace
    - run:
        name: Recursive attached workspace contents
        command: ls -A ~/attached_workspace
